### ISSUE TITLE
Add support for block devices

### ISSUE THREAD

**Issue by lucaswerkmeister** [dspinellis/pmonitor#1]
I tried to use `pmonitor` on a `dd` process that is currently backing up my hard disk, but the progress and ETA are nonsensical:

```
$ sudo pmonitor -i1 -f/dev/sdb
/dev/sdb 8952479744000% 
/dev/sdb 8953987072000% 
/dev/sdb 8955428864000% ETA -2:-31:-49
/dev/sdb 8956883763200% ETA -2:-15:-35
/dev/sdb 8958338662400% ETA -2:-7:-25
/dev/sdb 8959675596800% ETA -2:-4:-30
/dev/sdb 8961143603200% ETA -2:00:-40
/dev/sdb 8962624716800% ETA -2:-12:-31
^C
```

I assume this is because `/dev/sdb` is a block device, for which `ls -l` does not report a useful size. Would it be possible to add support for block devices?

**Comment by lucaswerkmeister** [comment]
I’d gladly send a pull request for this, but I can’t find a generic UNIX shell command to determine the size of a block device – most of the answers I can find on the internet involve commands from the `util-linux` package (`blockdev`, `fdisk`, `lsblk`) or Linux-specific API file systems (`/proc/partitions`, `/sys/class/block/*/size`).

@dspinellis would you be willing to merge a Linux-specific version? (It would only be used if `test -b` reports a block device – that much is provided by POSIX, at least.)

**Comment by dspinellis** [comment]
Sure, thank you!

**Comment by lucaswerkmeister** [comment]
Got it working just in time before my `dd` process finished, so I could still test it :)
