### ISSUE TITLE
Try to auto-detect the sysfs mount point

### ISSUE THREAD

**Issue by BenBE** [dspinellis/pmonitor#6]
The sysfs mount point should usually be detectable by asking for it in /proc/mounts or using the mount command:

With /proc/mounts:
```bash
grep ' sysfs ' /proc/mounts | cut '-d ' -f2
```

With mount
```bash
LANG=C mount | grep ' type sysfs ' | cut '-d ' -f3
```

If multiple results are given, any of them should be fine, but usually the first line should indicate an earlier mount. If none is found, a fallback to /sys might be used.

**Comment by BenBE** [comment]
Because you should avoid to hardcode paths that can be customized ... and checking for the sysfs mount point is reasonably simple.

At least a check for sysfs to be present, when trying to access its information would be nice.

**Comment by lucaswerkmeister** [comment]
I question the sanity of any system that doesn’t have sysfs mounted on `/sys`. NixOS is the only OS I’m aware of that probably doesn’t have `/sys`, but as far as I know they also don’t have `/dev` (I heard their only “standard” paths are `/bin/sh` and `/usr/bin/env`, the absolute minimum for compatibility), so our whole device detection logic doesn’t work there anyways.

Ultimately, you have to pick your poison, I believe… the current implementation (assuming standard mounts for `/dev` and `/sys`) should work for the vast majority of Linux systems, that’s good enough for me. Using `lsblk` requires a separate package (`util-linux`) that might not be installed everywhere, and auto-detecting mount points adds some extra complication to the script that IMHO isn’t worth it. (Of course, @dspinellis might disagree.)

**Comment by dspinellis** [comment]
Unless we have a concrete use case, let's not complicate code without reason.
